### ISSUE TITLE
VLists can have different types 

### ISSUE THREAD

**Issue by sourencho** [apollo-lang/apollo#30] opened 2015-05-05 16:06 UTC
for example: [1,2, (A4, \2)]

**Comment by benkogan** [comment] 2015-05-05 16:09
Are you using the most recent version? In mine, that doesn't type check:

```
apollo> [1,2, (A4, \2)]
Type exception: "list is irregular"
```

Or are you saying the issue is that this is not allowed and you think it should be?

**Comment by benkogan** [comment] 2015-05-05 16:11
Also see #29.

**Comment by sourencho** [comment] 2015-05-05 16:23
Yeah I'm saying that currently  [1,2, (A4, \2)] doesn't throw an error , and that it should throw an error. 

Although I did see some code that would take care of this in check.hs

```
  VList xs -> do
    t <- mapM typecheck xs
    if uniform t
    then return $ List (head t)
    else throwError $ TypeExcept "list is irregular" 
```

**Comment by SourenP** [comment] 2015-05-05 16:23
Yeah I'm saying that it works and that it shouldnt

**Comment by benkogan** [comment] 2015-05-05 16:25
It doesn't work when I run it. Can you confirm you've pulled and show me how you're running it? (REPL, stdin, etc)

**Comment by rezanayebi** [comment] 2015-05-05 16:27
```
apollo> a : [Int] = [1,2, (A4, \4)]
apollo> a
[1,2,Note (Pitch 69) (Duration 16)]
```

**Comment by benkogan** [comment] 2015-05-05 16:29
The issue isn't that VLists aren't type checked yet, it's that the type checker doesn't have type checking for definitions implemented yet.

As such, this is a duplicate of #22.

**Comment by sourencho** [comment] 2015-05-05 16:30
whoopsiedoodles

**Closed as completed by benkogan** 2015-05-05 16:29 UTC
